### ISSUE TITLE
【请更新书签：油猴/传统】 更新脚本节点 修复入口检测

### ISSUE THREAD

**Issue by noprogramming** [noprogramming/expanda#19]
当前脚本节点：
0 ZEIT (Google:TW)
https://expanda.org/
1 RawGit (Cloudflare:CT)
https://ghcdn.rawgit.org/noprogramming/expanda/master/
2 GitHub (Fastly:NTT)
https://noprogramming.github.io/expanda/

由于主站的ZEIT在个别时段会出现故障，GitHub自身速度又太慢（垃圾NTT），所以增加了基于Cloudflare的镜像，顺列第二位。【请更新油猴及传统书签】

修复了白屏检测，脚本会自动刷新。之前不小心改成了检测document.body（实际非空），造成无法执行COOKIE注入，带来不便请谅解。

**Comment by Lab-Heathcliff** [comment]
现在不白屏了，感谢

**Comment by Lab-Heathcliff** [comment]
ex点击加入收藏，小窗一直在err和loading之间闪

**Comment by noprogramming** [comment]
> 
> 
> ex点击加入收藏，小窗一直在err和loading之间闪

感谢反馈！
显示err是因为公共账号无法使用收藏、设置等功能。
一直闪是白屏检测把err的情况囊括了进去，已经改为更好的提示。
